import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sec' at '17. 8. 20 오후 9:10' with Gradle 2.14.1
 *
 * @author sec, @date 17. 8. 20 오후 9:10
 */
public class ApiTest {
    @Test 
    public void testSomeLibraryMethod() {
        assertTrue("someLibraryMethod should return 'true'", true);
    }
    
}
